language: node_js
node_js:
  - "0.10"
  
os:
  :windowsxp
  :linux
  
before_script:
  - "npm install"
  - "npm install istanbul"
  - "npm install coveralls"
  - "npm install -g mocha"


script:
  - "istanbul cover _mocha -- -R spec tests/nodejs/*.js"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
